"""Create ASCII-only production asset names for providers with filename limits."""

from pathlib import Path
import json
import re
import shutil


ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "src" / "main.jsx"
OPTIMIZED = ROOT / "public" / "images" / "optimized"
DELIVERY = ROOT / "site-public" / "images" / "site"
MANIFEST = ROOT / "src" / "imageAssets.js"
PATTERN = re.compile(r"I\('([^']+)'\)")


def main() -> None:
    source = SOURCE.read_text(encoding="utf-8")
    paths = sorted(set(PATTERN.findall(source)))
    DELIVERY.mkdir(parents=True, exist_ok=True)
    manifest = {}
    for index, original in enumerate(paths, start=1):
        source_path = (OPTIMIZED / original).with_suffix(".webp")
        output_name = f"image-{index:02d}.webp"
        if not source_path.exists():
            raise FileNotFoundError(source_path)
        shutil.copy2(source_path, DELIVERY / output_name)
        manifest[original] = output_name

    MANIFEST.write_text(
        "// Generated by scripts/make-safe-assets.py.\n"
        f"export const imageAssets = {json.dumps(manifest, ensure_ascii=False, indent=2)}\n",
        encoding="utf-8",
    )
    print(f"Prepared {len(manifest)} ASCII-only image files.")


if __name__ == "__main__":
    main()
